### ISSUE TITLE
ProjectShow.vue title shows default Vue favicon and Vite text

### ISSUE THREAD

**Issue by JordanPisani** [Commbocc/hc-cip-projects#37]
[Example](https://commbocc.github.io/hc-cip-projects/#/34985).

Ideally would display hcflgov favicon and project name.

**Comment by mccarthyk** [comment]
@JordanPisani 

A favicon you can use can be found [here](https://github.com/Commbocc/hc-animal-abuser-registry/blob/main/public/favicon.ico)

The [title](https://github.com/Commbocc/hc-cip-projects/blob/main/index.html#L7) can be "Hillsborough County CIP Projects"

**Comment by JordanPisani** [comment]
https://github.com/Commbocc/hc-cip-projects/pull/38
